// <auto-generated />
using System;
using Closer.DataService.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Closer.Migrations
{
    [DbContext(typeof(CloserContext))]
    partial class CloserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Closer.Entities.Discussion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<int>("DiscussionUserCreatorId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Moniker");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("DiscussionUserCreatorId");

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("Closer.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("InResponseToMessageID");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("MessageDiscussionId");

                    b.Property<int>("MessageUserId");

                    b.Property<string>("Moniker");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("MessageDiscussionId");

                    b.HasIndex("MessageUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Closer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Moniker");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Pseudo");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Closer.Entities.UserDiscussion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("DiscussionId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Moniker");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDiscussions");
                });

            modelBuilder.Entity("Closer.Entities.Discussion", b =>
                {
                    b.HasOne("Closer.Entities.User", "DiscussionUserCreator")
                        .WithMany()
                        .HasForeignKey("DiscussionUserCreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Closer.Entities.Message", b =>
                {
                    b.HasOne("Closer.Entities.Discussion", "MessageDiscussion")
                        .WithMany()
                        .HasForeignKey("MessageDiscussionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Closer.Entities.User", "MessageUser")
                        .WithMany()
                        .HasForeignKey("MessageUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Closer.Entities.UserDiscussion", b =>
                {
                    b.HasOne("Closer.Entities.Discussion", "Discussion")
                        .WithMany()
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Closer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
